id = "xonsh"
name = "Xonsh"
version = "0.2.0"
schema_version = 1
authors = ["Oscar Vargas Torres <contact@oscarvarto.mx>"]
description = "Xonsh shell language support - Python-powered shell with additional shell syntax"
repository = "https://github.com/oscarvarto/zed-xonsh"

[grammars.xonsh]
repository = "https://github.com/FoamScience/tree-sitter-xonsh"
rev = "b46f3a07a7fa12060e6daa21d828f32dd0a0ff61"

[language_servers.xonsh-lsp]
name = "xonsh-lsp"
languages = ["Xonsh"]
